#pragma once
#include "wavHeader.h"
#include <alsa/asoundlib.h>
#include <vector>
#include <memory>

#define PCM_MICROPHONE "plughw:3,0"

// Code generated by ChatGPT, edited by me.
// Assistance in understanding and implementing ALSA recording functionality provided by Github Copilot.

class AudioRecorder
{
public:
    AudioRecorder(bool recordToWav = false);
    
    bool startRecording(std::string filename = "recording.wav");
    
    void recordChunk();
    void stopRecording();
    
private:
    bool recordToWav = false;
    WAVHeader wavHeader;
    std::ofstream wavFile;
    int bytesRecorded = 0;

private:
    snd_pcm_t* pcmHandle;
    snd_pcm_hw_params_t* params;
    snd_pcm_uframes_t frames = 32;
    int pcm, dir;
    unsigned int rate = 16000; // Sample rate
    int channels = 1;
    snd_pcm_uframes_t framesPerPeriod = 32;
    std::vector<int16_t> buffer;    
    int bufferSize;
};